# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.calcTab = QtWidgets.QWidget()
        self.calcTab.setObjectName("calcTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.calcTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calcTable = QtWidgets.QTableView(self.calcTab)
        self.calcTable.setObjectName("calcTable")
        self.horizontalLayout.addWidget(self.calcTable)
        self.tabWidget.addTab(self.calcTab, "")
        self.contribTab = QtWidgets.QWidget()
        self.contribTab.setObjectName("contribTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.contribTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.contribTable = QtWidgets.QTableView(self.contribTab)
        self.contribTable.setObjectName("contribTable")
        self.horizontalLayout_2.addWidget(self.contribTable)
        self.tabWidget.addTab(self.contribTab, "")
        self.wlaTab = QtWidgets.QWidget()
        self.wlaTab.setObjectName("wlaTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wlaTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wlaTable = QtWidgets.QTableView(self.wlaTab)
        self.wlaTable.setObjectName("wlaTable")
        self.horizontalLayout_3.addWidget(self.wlaTable)
        self.tabWidget.addTab(self.wlaTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.messageLabel = QtWidgets.QLabel(self.centralwidget)
        self.messageLabel.setText("")
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout.addWidget(self.messageLabel, 3, 0, 1, 1)
        self.progressMsg = QtWidgets.QLabel(self.centralwidget)
        self.progressMsg.setMinimumSize(QtCore.QSize(500, 0))
        self.progressMsg.setMaximumSize(QtCore.QSize(300, 16777215))
        self.progressMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.progressMsg.setObjectName("progressMsg")
        self.gridLayout.addWidget(self.progressMsg, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(439, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.maxNaLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxNaLabel.setText("")
        self.maxNaLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxNaLabel.setWordWrap(False)
        self.maxNaLabel.setObjectName("maxNaLabel")
        self.gridLayout.addWidget(self.maxNaLabel, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 22))
        self.menubar.setObjectName("menubar")
        self.menuParameters = QtWidgets.QMenu(self.menubar)
        self.menuParameters.setObjectName("menuParameters")
        self.menuVista = QtWidgets.QMenu(self.menuParameters)
        self.menuVista.setObjectName("menuVista")
        self.menuImport = QtWidgets.QMenu(self.menuParameters)
        self.menuImport.setObjectName("menuImport")
        self.menuFunctions = QtWidgets.QMenu(self.menubar)
        self.menuFunctions.setObjectName("menuFunctions")
        self.menuC_lculo_de_profundidad = QtWidgets.QMenu(self.menuFunctions)
        self.menuC_lculo_de_profundidad.setObjectName("menuC_lculo_de_profundidad")
        self.menuC_lculo_de_di_metro = QtWidgets.QMenu(self.menuFunctions)
        self.menuC_lculo_de_di_metro.setObjectName("menuC_lculo_de_di_metro")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        self.menuExportarSwmm = QtWidgets.QMenu(self.menuExport)
        self.menuExportarSwmm.setObjectName("menuExportarSwmm")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionProject = QtWidgets.QAction(MainWindow)
        self.actionProject.setObjectName("actionProject")
        self.actionParameters = QtWidgets.QAction(MainWindow)
        self.actionParameters.setObjectName("actionParameters")
        self.actionPipes = QtWidgets.QAction(MainWindow)
        self.actionPipes.setObjectName("actionPipes")
        self.actionInspectionDevices = QtWidgets.QAction(MainWindow)
        self.actionInspectionDevices.setObjectName("actionInspectionDevices")
        self.actionMin_Excav = QtWidgets.QAction(MainWindow)
        self.actionMin_Excav.setCheckable(True)
        self.actionMin_Excav.setObjectName("actionMin_Excav")
        self.actionMin_Desnivel = QtWidgets.QAction(MainWindow)
        self.actionMin_Desnivel.setCheckable(True)
        self.actionMin_Desnivel.setObjectName("actionMin_Desnivel")
        self.actionAjuste_NA = QtWidgets.QAction(MainWindow)
        self.actionAjuste_NA.setObjectName("actionAjuste_NA")
        self.actionCalcular_DN_Creciente = QtWidgets.QAction(MainWindow)
        self.actionCalcular_DN_Creciente.setObjectName("actionCalcular_DN_Creciente")
        self.actionCalculara_DN = QtWidgets.QAction(MainWindow)
        self.actionCalculara_DN.setObjectName("actionCalculara_DN")
        self.actionCreateResultsLayer = QtWidgets.QAction(MainWindow)
        self.actionCreateResultsLayer.setObjectName("actionCreateResultsLayer")
        self.actionExportToXls = QtWidgets.QAction(MainWindow)
        self.actionExportToXls.setObjectName("actionExportToXls")
        self.actionResetDB = QtWidgets.QAction(MainWindow)
        self.actionResetDB.setObjectName("actionResetDB")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionResetear_Ajuste_NA = QtWidgets.QAction(MainWindow)
        self.actionResetear_Ajuste_NA.setObjectName("actionResetear_Ajuste_NA")
        self.actionReiniciar_DN = QtWidgets.QAction(MainWindow)
        self.actionReiniciar_DN.setObjectName("actionReiniciar_DN")
        self.actionCreateQiSwmmFile = QtWidgets.QAction(MainWindow)
        self.actionCreateQiSwmmFile.setObjectName("actionCreateQiSwmmFile")
        self.actionCreateQfSwmmFile = QtWidgets.QAction(MainWindow)
        self.actionCreateQfSwmmFile.setObjectName("actionCreateQfSwmmFile")
        self.actionDeleteActiveProject = QtWidgets.QAction(MainWindow)
        self.actionDeleteActiveProject.setObjectName("actionDeleteActiveProject")
        self.actionPublishProject = QtWidgets.QAction(MainWindow)
        self.actionPublishProject.setObjectName("actionPublishProject")
        self.actionBasic = QtWidgets.QAction(MainWindow)
        self.actionBasic.setCheckable(True)
        self.actionBasic.setChecked(True)
        self.actionBasic.setObjectName("actionBasic")
        self.actionDetailed = QtWidgets.QAction(MainWindow)
        self.actionDetailed.setCheckable(True)
        self.actionDetailed.setObjectName("actionDetailed")
        self.actionImportSelectedSegments = QtWidgets.QAction(MainWindow)
        self.actionImportSelectedSegments.setObjectName("actionImportSelectedSegments")
        self.actionImportFullNetwork = QtWidgets.QAction(MainWindow)
        self.actionImportFullNetwork.setObjectName("actionImportFullNetwork")
        self.menuVista.addAction(self.actionBasic)
        self.menuVista.addAction(self.actionDetailed)
        self.menuImport.addAction(self.actionImportSelectedSegments)
        self.menuImport.addAction(self.actionImportFullNetwork)
        self.menuParameters.addAction(self.actionProject)
        self.menuParameters.addAction(self.actionParameters)
        self.menuParameters.addAction(self.menuImport.menuAction())
        self.menuParameters.addAction(self.menuVista.menuAction())
        self.menuC_lculo_de_profundidad.addAction(self.actionMin_Excav)
        self.menuC_lculo_de_profundidad.addAction(self.actionMin_Desnivel)
        self.menuC_lculo_de_di_metro.addAction(self.actionCalcular_DN_Creciente)
        self.menuC_lculo_de_di_metro.addAction(self.actionCalculara_DN)
        self.menuC_lculo_de_di_metro.addAction(self.actionReiniciar_DN)
        self.menuFunctions.addAction(self.menuC_lculo_de_profundidad.menuAction())
        self.menuFunctions.addAction(self.menuC_lculo_de_di_metro.menuAction())
        self.menuFunctions.addAction(self.actionAjuste_NA)
        self.menuFunctions.addAction(self.actionResetear_Ajuste_NA)
        self.menuExportarSwmm.addAction(self.actionCreateQiSwmmFile)
        self.menuExportarSwmm.addAction(self.actionCreateQfSwmmFile)
        self.menuExport.addAction(self.actionCreateResultsLayer)
        self.menuExport.addAction(self.actionExportToXls)
        self.menuExport.addAction(self.menuExportarSwmm.menuAction())
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionPublishProject)
        self.menubar.addAction(self.menuParameters.menuAction())
        self.menubar.addAction(self.menuFunctions.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SANIBIDapp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calcTab), _translate("MainWindow", "Red básica"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contribTab), _translate("MainWindow", "Contribuciones"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wlaTab), _translate("MainWindow", "Nivel de agua"))
        self.progressMsg.setText(_translate("MainWindow", "Loading ..."))
        self.menuParameters.setTitle(_translate("MainWindow", "Configuración"))
        self.menuVista.setTitle(_translate("MainWindow", "Vista"))
        self.menuImport.setTitle(_translate("MainWindow", "Importar datos"))
        self.menuFunctions.setTitle(_translate("MainWindow", "Funciones"))
        self.menuC_lculo_de_profundidad.setTitle(_translate("MainWindow", "Cálculo de profundidad"))
        self.menuC_lculo_de_di_metro.setTitle(_translate("MainWindow", "Cálculo de diámetro"))
        self.menuExport.setTitle(_translate("MainWindow", "Exportación"))
        self.menuExportarSwmm.setTitle(_translate("MainWindow", "Generar Archivo INP (Swmm)"))
        self.actionProject.setText(_translate("MainWindow", "Proyecto"))
        self.actionParameters.setText(_translate("MainWindow", "Parámetros"))
        self.actionPipes.setText(_translate("MainWindow", "Tubos"))
        self.actionInspectionDevices.setText(_translate("MainWindow", "Dispositivos de Inspección"))
        self.actionMin_Excav.setText(_translate("MainWindow", "Min. Excav."))
        self.actionMin_Desnivel.setText(_translate("MainWindow", "Min. Desnivel"))
        self.actionAjuste_NA.setText(_translate("MainWindow", "Ajuste NA"))
        self.actionCalcular_DN_Creciente.setText(_translate("MainWindow", "Calcular DN Creciente"))
        self.actionCalculara_DN.setText(_translate("MainWindow", "Calculara DN"))
        self.actionCreateResultsLayer.setText(_translate("MainWindow", "Crear Capa QGIS"))
        self.actionExportToXls.setText(_translate("MainWindow", "Generar Hoja Impresión"))
        self.actionResetDB.setText(_translate("MainWindow", "Reinicializar BD"))
        self.action.setText(_translate("MainWindow", "Limpiar Ajuste NA"))
        self.actionResetear_Ajuste_NA.setText(_translate("MainWindow", "Reiniciar Ajuste NA"))
        self.actionReiniciar_DN.setText(_translate("MainWindow", "Reiniciar DN"))
        self.actionCreateQiSwmmFile.setText(_translate("MainWindow", "Caudal Inicial"))
        self.actionCreateQfSwmmFile.setText(_translate("MainWindow", "Caudal final"))
        self.actionDeleteActiveProject.setText(_translate("MainWindow", "Borrar Proyecto Actual"))
        self.actionPublishProject.setText(_translate("MainWindow", "publish project"))
        self.actionBasic.setText(_translate("MainWindow", "Basica"))
        self.actionDetailed.setText(_translate("MainWindow", "Detallada"))
        self.actionImportSelectedSegments.setText(_translate("MainWindow", "Sólo tramos seleccionados"))
        self.actionImportFullNetwork.setText(_translate("MainWindow", "Red completa"))
