# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/swmm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SwmmExportDialog(object):
    def setupUi(self, SwmmExportDialog):
        SwmmExportDialog.setObjectName("SwmmExportDialog")
        SwmmExportDialog.resize(525, 209)
        self.verticalLayout = QtWidgets.QVBoxLayout(SwmmExportDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(SwmmExportDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.fileName = QtWidgets.QLineEdit(self.frame)
        self.fileName.setGeometry(QtCore.QRect(153, 90, 221, 25))
        self.fileName.setObjectName("fileName")
        self.selectFileButton = QtWidgets.QPushButton(self.frame)
        self.selectFileButton.setGeometry(QtCore.QRect(390, 90, 80, 25))
        self.selectFileButton.setObjectName("selectFileButton")
        self.fileNameLabel = QtWidgets.QLabel(self.frame)
        self.fileNameLabel.setGeometry(QtCore.QRect(10, 95, 137, 17))
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.finalFlowRadioButton = QtWidgets.QRadioButton(self.frame)
        self.finalFlowRadioButton.setGeometry(QtCore.QRect(247, 38, 250, 23))
        self.finalFlowRadioButton.setObjectName("finalFlowRadioButton")
        self.initialFlowRadioButton = QtWidgets.QRadioButton(self.frame)
        self.initialFlowRadioButton.setGeometry(QtCore.QRect(10, 38, 231, 23))
        self.initialFlowRadioButton.setChecked(True)
        self.initialFlowRadioButton.setObjectName("initialFlowRadioButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 10, 171, 17))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(SwmmExportDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SwmmExportDialog)
        QtCore.QMetaObject.connectSlotsByName(SwmmExportDialog)

    def retranslateUi(self, SwmmExportDialog):
        _translate = QtCore.QCoreApplication.translate
        SwmmExportDialog.setWindowTitle(_translate("SwmmExportDialog", "saniHUB RedBasica"))
        self.selectFileButton.setText(_translate("SwmmExportDialog", "..."))
        self.fileNameLabel.setText(_translate("SwmmExportDialog", "Select the output file"))
        self.finalFlowRadioButton.setText(_translate("SwmmExportDialog", " Final flow (Max. final flow - k1*k2)"))
        self.initialFlowRadioButton.setText(_translate("SwmmExportDialog", "Initial flow (Average initial flow)"))
        self.label.setText(_translate("SwmmExportDialog", "Export .inp with:"))
